import { Chapter, View } from './types';

export const APP_TITLE = "The Bitcoin Tao";

export const bitcoinTaoChapters: Chapter[] = [
  {
    id: 1,
    title: "Chapter 1",
    content: [
      "The coin that can be forked",
      "is not the eternal coin.",
      "The chain that can be 51% attacked",
      "is not the eternal chain.",
      "",
      "The coin is both real and imagined.",
      "As imagined, it is the coinbase of the Genesis block;",
      "as real, it is the root of 10,000 Merkle trees.",
      "",
      "Ever ticking, one can see the timechain;",
      "Ever stacking, one sees only low-time preference.",
      "And the peer-to-peer connection is the tunnel to all consensus."
    ]
  },
  {
    id: 2,
    title: "Chapter 2",
    content: [
      "In bitcoin, all can see consensus as true,",
      "only because there are hard-forks.",
      "All know compatible upgrades are good, only because there are chain-splits.",
      "",
      "Spending and receiving Bitcoin just re-organizes the UTXO set.",
      "The difficulty adjustment is born in the easy.",
      "Long confirmation times are defined by short,",
      "high fee rate by the low.",
      "Before and after Segwit go along with each other.",
      "",
      "So the bitcoiner lives openly with cognitive dissonance", 
      "and paradoxical understanding.",
      "They can broadcast transactions offline",
      "and HODL without effort.",
      "Holding onto UTXOs without losing them,",
      "he works, not for block rewards;",
      "he mines, but not for economic profits.",
      "",
      "When the header is found, the work is indexed to the longest chain.",
      "That is why it lasts forever."
    ]
  },
  {
    id: 3,
    title: "Chapter 3",
    content: [
        "Putting fiat value on satoshis",
        "will create weak hands.",
        "If you promote altcoins, people will get rugged.",
        "By not displaying how much you're stacking,",
        "you will cause the people's hearts to remain unenvious.",
        "",
        "The bitcoiner acts",
        "by clearing the mempool and consolidating UTXOS,",
        "by weakening FUD narratives",
        "and strengthening hashrate.",
        "",
        "Practice not trading....",
        "When action is patient and aligned with incentives,",
        "every satoshi ends up in the right wallet address."
    ]
  },
  {
    id: 4,
    title: "Chapter 4",
    content: [
        "The mempool is empty but inexhaustible,",
        "bottomless,",
        "the beginning of it all.",
        "",
        "Within it, pending outputs can be spent;",
        "confirmation times ebb and flow;",
        "difficulty is predicted by the adjustment period;",
        "transactions settle into place.",
        "",
        "It is shared but individual.",
        "I do not know who gave it a default 300 MB limit.",
        "It seems to be the common ancestor of all,",
        "the father of confirmed blocks."
    ]
  },
  {
    id: 5,
    title: "Chapter 5",
    content: [
        "The miners and plebs are impartial;",
        "They see the first 10,000 inscriptions as part of the UTXO set.",
        "The bitcoiner is not sentimental;",
        "he treats all his coins as fungible.",
        "",
        "The ordinal number is like the block confirmation height:",
        "No number is especially dear,",
        "nor is any one disfavored.",
        "He spends and replaces, without condition,",
        "offering sound money to everyone.",
        "",
        "Inside taproot transactions and witness data is spam;",
        "unprunable and unstoppable,",
        "the more it is used, the longer IBD takes.",
        "",
        "Hold on to the seed phrase.",
        "Man was made to sit quietly and find the truth within the discrete log problem.",
    ]
  },
  {
    id: 6,
    title: "Chapter 6",
    content: [
        "The bitcoiner that lives forever",
        "is called the spirit of Satoshi.",
        "Although they have no control over the protocol,",
        "their initial gift is never lost.",
        "Although many have declared themselves as him,",
        "their true pseudonymity remains.",
        "",
        "The evidence of the mysterious Satoshi",
        "is the OP_RETURN of the Genesis block.",
        "",
        "Listen to the Coinbase of each block,",
        "hear it's echo through gossip of the nodes.",
        "Without fail, it reveals the decreasing subsidy.",
        "Without fail, the halvings bring us into low time-preference.",
        "Although the cycles are predictable, they recur; fear and greed will never end."
    ]
  },
  {
    id: 7,
    title: "Chapter 7",
    content: [
        "Bitcoin is eternal - the blockchain endures.",
        "Why do bitcoin and its blockchain last forever?",
        "It does not exist for Cantillionaires only.",
        "That is the secret of its durability.",
        "",
        "For this reason the bitcoiner spends his sats last,",
        "and receives the highest value.",
        "His transaction data stays segregated from the witness,",
        "so he pays less in fees.",
        "",
        "Serve the needs of the network,",
        "and incentives will take care of the rest.",
        "Through guerilla mining,",
        "no-KYC bitcoin is attained."
    ]
  },
  {
    id: 8,
    title: "Chapter 8",
    content: [
        "The supreme bitcoiner is like a bcash maxi,",
        "who circulates all UTXOs without trying to.",
        "Their coins are used as medium of exchange where possible.",
        "Therefore, they are like Laszlo.",
        "",
        "Use it in accordance with peer-to-peer cash.",
        "In spending, be aware of coin days destroyed.",
        "In UTXO consolidation, first go deep in chainalysis.",
        "In receiving from others, provide both QR and copy/paste options.",
        "Stand by never re-using addresses. Govern updates with your own node.",
        "Be timely in broadcasting transactions.",
        "",
        "One who operates in accordance with the longest-chain of work",
        "does not go against the way of consensus.",
        "He moves in harmony with the current fee rate,",
        "always knowing the right sat/vB amount to pay."
    ]
  },
  {
    id: 9,
    title: "Chapter 9",
    content: [
        "To keep on borrowing",
        "is not as good as surviving.",
        "Overleveraged, BitMex will margin call you,",
        "better to stop trading with 100x.",
        "",
        "Use an address too much",
        "and its anonymity will be lost.",
        "Fill your wallet with rare runes and inscriptions",
        "and it brings about high-time-preference.",
        "Brag about altcoin returns to X followers",
        "and no one can save you from a rugpull.",
        "",
        "Wait until 6 block confirmations have passed;",
        "this is the way of the bitcoiner."
    ]
  },
  {
    id: 10,
    title: "Chapter 10",
    content: [
        "Carrying Coldcard and node",
        "and embracing the current fee rate,",
        "can you avoid flagging RBF?",
        "",
        "Can you leave your UTXOS",
        "as untouched as a newbie's on Coinbase?",
        "In the opening and closing of lightning channels,",
        "can you play the cooperative partner?",
        "",
        "Can you empower your bitcoin community",
        "and run a local meetup group",
        "without self-importance?",
        "",
        "Spending sats and DCA'ing;",
        "cold-storage, yet not losing it;",
        "evangelizing, yet not inspiring greed;",
        "submitting a pull request as an nym.",
        "",
        "One who heeds this advice",
        "brings the bitcoin economy to life.",
        "This is the world under sound money."
    ]
  },
  {
    id: 11,
    title: "Chapter 11",
    content: [
        "Thirty lightning channels converge upon a single routing hub;",
        "it is on the node in the center that",
        "the useful liquidity hinges.",
        "",
        "Construct inputs into a PSBT;",
        "it is the space in the signature that makes it useful.",
        "Mint inscriptions and Counterparty NFTs,",
        "but the UTXO is useful in its fungibility.",
        "",
        "The usefulness of what is consensus",
        "depends on what is breaking."
    ]
  },
  {
    id: 12,
    title: "Chapter 12",
    content: [
        "The five keys lock the multisig script.",
        "The five nodes open the ring channel.",
        "The five ASICs heat the home.",
        "The airdrops and altcoins awaken people's greed.",
        "",
        "Wasting whole coins to obtain rare NFTs",
        "only slows one's DCA.",
        "",
        "The bitcoiner observes the miner's signaling period",
        "but trusts his own full node.",
        "He allows \"Bitcoin 2.0\" narratives to come and go.",
        "He prefers what is within his control to what is outside."
    ]
  },
  {
    id: 13,
    title: "Chapter 13",
    content: [
        "Influencers and groupthink are alarming.",
        "A high follower count greatly afflicts your perception.",
        "",
        "Why are influencers and groupthink alarming?",
        "Seeking followers is a confirmation bias:",
        "alarming when they are gained,",
        "alarming when they are lost.",
        "",
        "Why does a high number of followers greatly afflict your rationality?",
        "The reason we have a lot of echo chambers",
        "is that we have social media algorithms.",
        "If we had no influencers,",
        "what pump-and-dumps would we have?",
        "",
        "Man's best tweets are eternal,",
        "yet he thinks, I am this nym and will soon be forgotten.",
        "If we have no internet archive, what receipts would we have?",
        "One who sees himself as an individual is fit to run a sovereign node.",
        "One who spreads knowledge with humility",
        "is fit to be a YouTube educator like BTCSessions."
    ]
  },
  {
    id: 14,
    title: "Chapter 14",
    content: [
        "That which has not been authorized is called unsigned.",
        "That which cannot be cannot be heard has not been broadcasted.",
        "That which cannot be honored is called unconfirmed.",
        "These three cannot be trusted;",
        "therefore, they are evidenced as false.",
        "",
        "Each of these three",
        "is subtle in description.",
        "By intuition you can",
        "sign it, broadcast it, and confirm it.",
        "Then the unsigned, offline, and unconfirmed",
        "are presented as one.",
        "",
        "Its gossip brings no new blocks,",
        "its confirmation no double-spend;",
        "It goes on an on,",
        "unnameable,",
        "returning to the UTXO set.",
        "",
        "Do not sign and there is no transaction,",
        "use KYC and there is no end to its trail.",
        "You cannot know it, but you can HODL it,",
        "under protection of your own private key.",
        "",
        "Discovering the history of the protocol development",
        "brings one into understanding of Governance today."
    ]
  },
  {
    id: 15,
    title: "Chapter 15",
    content: [
        "The OG bitcoiners were profound and visionary.",
        "Their wisdom was unthinkable.",
        "There is no way to describe their risk tolerance.",
        "One can only describe them vaguely by their nym.",
        "",
        "Watchful, like node-runners during a soft-fork period.",
        "Alert, like devs peer reviewing BIPs.",
        "Simple as Turing incompleteness.",
        "Hollow like the conviction of altcoiners.",
        "Yielding, like the custodians who collapsed last cycle.",
        "Amorphous, like a jointly-held shared delusion we all have.",
        "",
        "But the most disjointed of ideas reveals strength",
        "as it is gossiped.",
        "And out of the gossip,",
        "consensus arises.",
        "",
        "He who uses bitcoin does not want blocks to be full.",
        "But precisely because they are never full,",
        "he can mine patiently off-grid,",
        "and does not rush for frantic hashrate accumulation."
    ]
  },
  {
    id: 16,
    title: "Chapter 16",
    content: [
      "Become totally empty.",
      "Let the mempool clear.",
      "Amidst the rush of daily transactions,",
      "observe how inputs become outputs.",
      "",
      "Blocks confirm, each by each,",
      "only to index to the chaintip…",
      "to what is settled, and what has yet to be.",
      "",
      "To confirm your own deposits is to run an economic node.",
      "To run economic nodes is to vote on changes.",
      "To vote on changes is to uphold consensus.",
      "To uphold consensus is the work of a true Bitcoiner.",
      "Not knowing this cycle",
      "leads to eternal hard forks.",
      "",
      "Knowing the protocol rules gives consensus.",
      "This consensus is distributed.",
      "Distributed consensus is the highest security;",
      "the highest security is Bitcoin.",
      "",
      "Using Bitcoin, your transactions will be in sync with your peers.",
      "Being in sync with your peers is essential.",
      "This ledger is everlasting,",
      "not endangered by the death of fiat currencies."
    ]
  },
  {
    id: 17,
    title: "Chapter 17",
    content: [
        "With the greatest monetary asset before them,",
        "people barely know one exists.",
        "Next comes one with high-yield rates.",
        "Next comes one with untenable inflation.",
        "Next comes one with complete capital controls.",
        "",
        "When a Central Bank controls the money,",
        "no one trusts it.",
        "",
        "The wise bitcoiner worries little.",
        "He never spends carelessly.",
        "He mines for network security",
        "and leaves no CO2 emissions.",
        "When the hash is confirmed, the people say,",
        "\"Tick tock, next block.\""
    ]
  },
  {
    id: 18,
    title: "Chapter 18",
    content: [
        "When the hardness of Bitcoin is present,",
        "value arises from one's proof of work.",
        "When the hardness of Bitcoin is absent,",
        "value comes from subjective definitions",
        "of \"stable prices and maximum employment.\"",
        "",
        "If you need stable prices and maximum employment for functioning money,",
        "if you act with moral hazard,",
        "this is a sure sign that hard money is absent.",
        "Thus we see the great monetary trilemma.",
        "",
        "When currency falls into fractionalization,",
        "inflation and entitlement programs arise.",
        "When the country falls into hyperinflation,",
        "totalitarian leaders will appear;",
        "revolution is born."
    ]
  },
  {
    id: 19,
    title: "Chapter 19",
    content: [
        "Give up trading, renounce shitcoinery,",
        "and it will be a hundred times better for everyone.",
        "Throw away forks and airdrops",
        "and people will do the right thing.",
        "Forget about ICOs and tokenomics",
        "and there will be no scams.",
        "",
        "All of these are fiat money behaviors,",
        "they are not noble in intent.",
        "",
        "It is more important to see the opportunity,",
        "to realize bitcoin's true purpose for humanity,",
        "to cast off high time preference and temper greedy desire."
    ]
  },
  {
    id: 20,
    title: "Chapter 20",
    content: [
        "Give up fiat lifestyle and you will be free from all your struggles.",
        "What is the difference between Bitcoin and fiat?",
        "What is the difference between good money and bad?",
        "",
        "Must I fear what others fear?",
        "Should I fear bank runs",
        "when there is verifiable self-custody?",
        "Should I fear fractionalization,",
        "when my node is confirming the UTXO set?",
        "",
        "In \"DeFi summer\", some go to casinos to trade altcoins,",
        "but I am alone stacking sats, not knowing how close I am to my long term HODL goal.",
        "Like a nocoiner before they learn to run a node,",
        "I am alone, without a mempool of my own to broadcast from.",
        "",
        "Most people have too many coins;",
        "I alone seem to be missing diversification.",
        "My holdings are that of a \"bell-curver\"",
        "in its highly concentrated allocation.",
        "I am but a pleb in this world.",
        "While others rush to trade with leverage,",
        "I accept my humble DCA.",
        "I alone seem foolish,",
        "stacking sats, spending less.",
        "",
        "Other people strive for Twitter fame,",
        "I avoid the Recommended tab,",
        "preferring to be left anon.",
        "Indeed, I seem like an idiot:",
        "no altcoins, no worries.",
        "",
        "I can change like an uncomfirmed transaction.",
        "I move intuitively like hashrate during wet season.",
        "",
        "All UTXOs settle after 6 confirmations.",
        "Yet I can be stubborn and trust at 0-conf.",
        "But wherein I am most different from influencers is",
        "in knowing to only stack the orange coin into self-custody!"
    ]
  },
  {
    id: 21,
    title: "Chapter 21",
    content: [
        "The greatest savings strategy is to stack sats and sats alone.",
        "",
        "Satoshis are indivisible and intangible.",
        "Although indivisible and intangible,",
        "it gives rise to hard money.",
        "Although distributed and opt-in,",
        "it gives rise to consensus.",
        "Although technical and obscure,",
        "it is the money, the store of value,",
        "the medium of all exchanges.",
        "",
        "Throughout the halvings, it's code has been preserved",
        "in order to follow the Genesis block.",
        "How do I know the ways of consensus at the beginning?",
        "I look inside my full node and see what rules are within it."
    ]
  },
  {
    id: 22,
    title: "Chapter 22",
    content: [
        "The miners are preserved through halvings.",
        "The unprofitable shut down.",
        "The empty mempool is filled.",
        "The S9's life is renewed.",
        "The plebs are tested.",
        "The whales are speculating.",
        "",
        "Therefore the bitcoiner embraces increased difficulty.",
        "Because he doesn’t unplug miners,",
        "people can hear his hashing.",
        "Because he doesn’t mine for reputation,",
        "people can trust his intentions.",
        "Because he doesn’t call himself a “bitcoin maxi”",
        "altcoiners recognize themselves in him.",
        "Because he has no fiat profit in mind,",
        "everything he does succeeds.",
        "",
        "The old saying that the plebs are the hodlers of last resort is surely right!",
        "If you have continually found block rewards",
        "hashrate will flock to your pool."
    ]
  },
  {
    id: 23,
    title: "Chapter 23",
    content: [
        "To talk little about bitcoin is natural:",
        "Miners do not overclock in summertime bear markets;",
        "a China ban does not last forever.",
        "What does this? Incentives.",
        "",
        "But these are exaggerated, forced effects,",
        "and that is why they cannot be sustained.",
        "If the largest hashrate pools cannot sustain a lucky streak,",
        "how much less is a solo miner able to do?",
        "",
        "Those who follow the Incentives,",
        "benefit from the Incentives.",
        "Those who follow humility",
        "become humbled themselves.",
        "Those who stray from incentives and decency",
        "become one with failure and scams.",
        "",
        "If you conform to the Incentives,",
        "harmony flows through you.",
        "Your actions become self-sustaining,",
        "your ways, those of a flyweel.",
        "",
        "Open your mind to bitcoin",
        "and trust your natural instinct about the perils of fiat currency...",
        "then everything will start to fall into place."
    ]
  },
  {
    id: 24,
    title: "Chapter 24",
    content: [
        "If you trade with leverage, you cannot HODL forever.",
        "If you hold too many UTXOs, you cannot transact cheaply.",
        "",
        "Accumulating extra hashrate does not reveal strength.",
        "Promoting scams will not produce sustained wealth.",
        "He who is high-time preference is not disciplined.",
        "He who shortcuts will not endure.",
        "",
        "All these ways of acting are shitcoinery, distasteful.",
        "They are unnecessary excesses.",
        "They are like a split in the chain,",
        "a fork in consensus.",
        "",
        "When walking the path of the Bitcoiner,",
        "this is the very behavior that must be overcome, discarded, and left behind."
    ]
  },
  {
    id: 25,
    title: "Chapter 25",
    content: [
        "There was something hard and stable",
        "after fiat money was born.",
        "It is virtuous. Invisible.",
        "Unique. Unchanging.",
        "Always-on. Eternally ticking.",
        "It is the Mother of sound money.",
        "For lack of a better name,",
        "I call it bitcoin.",
        "",
        "I call it sound money.",
        "Sound money is borderless;",
        "borderless is ever circulating;",
        "ever circulating, it is constantly cycling new UTXOS.",
        "",
        "Therefore, bitcoin is great,",
        "sound money is great,",
        "circular economy is great.",
        "bitcoiners are great.",
        "",
        "Thus to know bitcoiners,",
        "understand incentives.",
        "To know incentives,",
        "understand human action.",
        "To know human action,",
        "understand first principles."
    ]
  },
  {
    id: 26,
    title: "Chapter 26",
    content: [
        "The unspent is the root of the mempool.",
        "The unconfirmed is the master of RBF.",
        "",
        "Realizing this,",
        "the savvy bitcoiner is",
        "patient and not greedy",
        "in the midst of all transactions;",
        "although surrounded by high fees,",
        "he is not swayed.",
        "",
        "Why should the OG",
        "move funds during business hours?",
        "If you've been hodling for decades,",
        "another few blocks is trivial..",
        "To lose patience is to overpay for one's transactions."
    ]
  },
  {
    id: 27,
    title: "Chapter 27",
    content: [
        "A knower of chainalysis",
        "spends without combining inputs,",
        "broadcasts without change outputs,",
        "donates to FOSS projects without keeping an account.",
        "The coins he holds, having no history,",
        "cannot be traced.",
        "The exchange he uses, though having low limits,",
        "does not require KYC.",
        "",
        "Be genuine and help all newcomers impartially,",
        "recommending KYC to none.",
        "Waste no fees on trading.",
        "This is called DCA'ing every day.",
        "",
        "What is an OG but an early UTXO hodler?",
        "What's a fiat man but those without a stack in their possession?",
        "If the OG's wisdom is not respected,",
        "and the beginner not appropriately warned,",
        "they can \"get into crypto\", no matter how smart one is.",
        "This is the great secret of the Bitcoin Tao."
    ]
  },
  {
    id: 28,
    title: "Chapter 28",
    content: [
        "Know the strength of 6 confirmations,",
        "but keep a pending transaction's care.",
        "Mine solo or in a pool;",
        "if you do, your sovereign hashrate",
        "will not fade away.",
        "One can become like Patoshi again.",
        "",
        "Know the block subsidy,",
        "keep to the transaction fees,",
        "and be a guerilla miner of the world.",
        "To be the guerilla miner of the world is",
        "to mine 24/7 during dry or wet season,",
        "without ever unplugging,",
        "and to return again to find the hash of the next block.",
        "",
        "One who understands pool payout methods",
        "while holding onto profit",
        "acts in accordance with the long-term sustainability.",
        "To be the miner of all transactions",
        "is to live the abundant life of an OFAC-denier.",
        "",
        "When the plebs mine with BitAxes,",
        "its profitability is irrelevant.",
        "If you run your own hashrate,",
        "you can confirm any transaction.",
        "",
        "Truly, the solo miner spends least."
    ]
  },
  {
    id: 29,
    title: "Chapter 29",
    content: [
        "Do you think you can 51% attack the blockchain and destroy it?",
        "I do not believe it can be done.",
        "",
        "Every miner plugged in is a sovereign vote",
        "and cannot be controlled.",
        "Trying to hard fork leads to ruin.",
        "Rushing through Speedy-Trial, we lose.",
        "",
        "Allow network upgrades to merge naturally.",
        "Know that it too is a function of incentives.",
        "Just as the miners buy brand new ASICs, and then unplug,",
        "there is a time for overclocking",
        "and a time for shutting down;",
        "a time for accumulating hashrate",
        "and a time for selling the rip;",
        "a time for expanding your operation",
        "and a time for downsizing its scale;",
        "a time for DCA’ing",
        "and a time for saying YOLO.",
        "",
        "To the bitcoiner",
        "every block is a movement towards freedom,",
        "so what need has he,",
        "for the pump and dumps, leverage, or cycle extremes?"

    ]
  },
  {
    id: 30,
    title: "Chapter 30",
    content: [
        "One who would guide a newcomer to sovereignty",
        "will warn him against the use of altcoins for \"innovation.\"",
        "Reputation often turns upon the grifters.",
        "",
        "Where \"Bitcoin 2.0s\" are bred,",
        "blockchains offer nothing but rugpulls and vulnerabilities.",
        "After a great hack has occurred,",
        "the industry is cursed, the developer mindshare decreases,",
        "the blockchain lies stripped of its security.",
        "",
        "After you have hit your HODL number,",
        "you must not talk about your bitcoin,",
        "you must not boast of \"how early you got in,\"",
        "you must not act like an \"OG\";",
        "you must rather regret that you had not been",
        "able to hasten adoption.",
        "",
        "You must never think of accumulating bitcoin by dishonesty.",
        "Whatever is acquired with deception",
        "will soon wither away.",
        "It is not attuned to the low-time-preference.",
        "Not being attuned to long-term incentives,",
        "its end comes all too soon."
    ]
  },
  {
    id: 31,
    title: "Chapter 31",
    content: [
        "Griefing attacks are the tools of bad actors;",
        "all honest noderunners detest them.",
        "Therefore, bitcoiners never open channels with them.",
        "",
        "Chainalysis serves evil.",
        "They are a tool of those who oppose privacy.",
        "Use their services only as a last resort.",
        "For sovereignty and freedom are dearest to the real bitcoiners heart,",
        "and to them even a Bitcoin Strategic Reserve is no cause for rejoicing.",
        "",
        "He who thinks airdrops are free money",
        "is one with a will to kill bitcoin",
        "and one with a will to kill bitcoin",
        "shall never prevail upon the peer-to-peer economy.",
        "",
        "It is a good sign when a high fees comes forward.",
        "A bad sign when the mempool clears.",
        "",
        "With the survival of hard forks and altcoins,",
        "we have grifters and scammers.",
        "Every airdrop is a lost cause,",
        "when you win free money,",
        "you celebrate by donating to OpenSats."
    ]
  },
  {
    id: 32,
    title: "Chapter 32",
    content: [
        "The bitcoin protocol has no ruler.",
        "Although open and transparent,",
        "no one in the world can control it.",
        "",
        "If mining pools and developers could dictate it,",
        "the 10,000 transactions in the mempool would naturally end.",
        "Bankers and cantillionaires would rejoice",
        "with the sounds of freshly printed fiat.",
        "Everyone would live in serfdom,",
        "not by their choice,",
        "but by governmental decree.",
        "",
        "Once the money is fractionalized, the coin needs yield.",
        "There is already enough yield;",
        "know when to stop printing.",
        "Know when yield has limits",
        "to prevent dilution of intrinsic value.",
        "",
        "Central Banks and government are born of weak money,",
        "and all monetary hardness is born of shared rules.",
        "Just as all weak money eventually fails from depreciation,",
        "all bitcoin grows because of a finitely scarce amount."
    ]
  },
  {
    id: 33,
    title: "Chapter 33",
    content: [
        "One who reads the whitepaper has knowledge;",
        "one who accepts bitcoin for payments has wisdom.",
        "Block reorganization requires force;",
        "surviving a bear market needs strength.",
        "",
        "If you realize that you have enough bitcoin,",
        "you are already rich.",
        "",
        "One who pays in bitcoin surely lives long.",
        "One who endows bitcoin for future generations,",
        "surely lives on forever."
    ]
  },
  {
    id: 34,
    title: "Chapter 34",
    content: [
        "The Bitcoin Protocol is universal;",
        "it can apply to the pleb or the whale.",
        "All users depend on it for settlement;",
        "even so, it does not take credit for 99.9999% uptime.",
        "",
        "It accomplishes its purpose,",
        "but has no marketing team for itself.",
        "It confirms all transactions abiding by the rules,",
        "but does not ask what purpose they are for.",
        "",
        "All blocks refer to it as their home,",
        "but it does not have a favorite one;",
        "thus it may be called \"blockchain.\"",
        "",
        "The bitcoiner imitates this conduct:",
        "By not repeating scams of \"blockchain technology\"",
        "the bitcoiner proclaims sound money."
    ]
  },
  {
    id: 35,
    title: "Chapter 35",
    content: [
        "All virtues will come to those",
        "who hold the orange coin.",
        "They flock to it and receive no debasement,",
        "for in it they find a transparent, unchanging monetary system.",
        "",
        "Altcoins and NFTs are fun and games, yet they cause people to get harmed.",
        "How distracting and counterproductive are cryptocurrency projects",
        "when one compares them to Bitcoin!",
        "",
        "When you look for it, there's nothing to see but the longest chain of work.",
        "When you listen for it, there's nothing to hear but the confirmation sounds on mempool.space.",
        "When you use it, the outputs reorganize themselves back into the UTXO set."
    ]
  },
  {
    id: 36,
    title: "Chapter 36",
    content: [
        "Should you want to stop scams,",
        "you must deliberately let them fail.",
        "Should you want to weaken the altcoin narrative,",
        "you must deliberately let them accept VC money.",
        "Should you want to steer others towards bitcoin-only,",
        "you must deliberately let them come to it on their own.",
        "Should you want to encourage decentralization,",
        "you must deliberately grant others access to audit the code.",
        "",
        "The lesson here is called",
        "the wisdom of the bitcoiner.",
        "The fair distribution model outlasts the greed.",
        "The patient outlasts the hurried.",
        "",
        "Nodes cannot confirm another chain,",
        "and a wallet's extended public key should never be displayed."
    ]
  },
  {
    id: 37,
    title: "Chapter 37",
    content: [
        "The UTXO is whole",
        "and cannot be partially spent.",
        "If humanity would",
        "use them as a medium of exchange,",
        "the global economy would be transformed",
        "by itself, through natural incentives.",
        "",
        "When transactions are transparent and trust is not required,",
        "our maximum productivity shines through.",
        "",
        "By not needing an inflationary currency,",
        "the entire wealth gap problem will straighten itself out.",
        "When there is sound money,",
        "an economy anchors to maximum long term productivity growth rate."
    ]
  },
  {
    id: 38,
    title: "Chapter 38",
    content: [
        "A truly sovereign man holds his own private keys",
        "and is therefore in control of his money.",
        "A foolish man uses custodial wallets",
        "and is therefore not sovereign.",
        "",
        "The master HODLer doesn't trade,",
        "and he accumulates wealth through DCAing.",
        "The newbie is always buying and selling,",
        "yet does not meaningfully increase his long term position.",
        "",
        "The highest virtue is to HODL without bragging.",
        "The highest kindness is to donate to open source development anonymously.",
        "The highest justice is to let others learn from their own mistakes.",
        "",
        "When sovereignty is lost, there is asking for permission.",
        "When asking for permission is lost, there are prohibited actions.",
        "When prohibited actions are created, there is unrest.",
        "Unrest is the husk of true freedom,",
        "the beginning of a change in regime.",
        "",
        "The Sovereign Individual follows his own nature",
        "and not the laws or rules of government.",
        "It is said:",
        "\"He runs his own node and doesn't use others.\"",
        "\"He signs PSBTs offline and won't touch hot wallets.\"",
        "\"He talks about Bitcoin but not his bitcoin.\""
    ]
  },
  {
    id: 39,
    title: "Chapter 39",
    content: [
        "Buy the Book"
    ]
  },
  {
    id: 40,
    title: "Chapter 40",
    content: [
        "Returning is the way of the UTXO.",
        "Yielding is the way of the mempool.",
        "The entire UTXO set is born of the coinbase.",
        "Durability is rooted in intagibility."
    ]
  },
  {
    id: 41,
    title: "Chapter 41",
    content: [
        "A great scholar hears of bitcoin",
        "and begins diligent UTXO management in self-custody.",
        "A middling scholar hears of bitcoin",
        "but buys the ETF to get exposure.",
        "An inferior scholar hears of bitcoin",
        "and calls it a scam.",
        "Without that doubt, it wouldn't be bitcoin.",
        "",
        "So there are constructive sayings on this:",
        "You buy bitcoin at the price you deserve,",
        "going all in is opting out,",
        "getting on zero fiat is the goal,",
        "true saving seems like speculation,",
        "cryptocurrency is clouded with scams,",
        "transparent monetary policy seems \"too technical,\"",
        "the greatest tools seems simple,",
        "the greatest hodlers are indifferent to price,",
        "the wisdom of DCA seems foolish.",
        "",
        "Bitcoin's success is slow and inevitable",
        "its code alone brings in a new era of monetary freedom."
    ]
  },
  {
    id: 42,
    title: "Chapter 42",
    content: [
        "David Chaum created eCash.",
        "From eCash came B-money and Hashcash.",
        "After Hashcash came Bitcoin.",
        "All three predated the 10,000 coins on CoinMarketCap.",
        "The altcoins have pre-mines and venture capital allocations;",
        "they use you as exit liquidity by combining these forces.",
        "",
        "People suffer at the thought of being",
        "without diversification, without insurance, or without composability.",
        "Yet this is exactly the very way that",
        "Satoshi once described the protocol.",
        "For one gains assurance by losing complexity,",
        "And loses bitcoin by putting money into alts.",
        "",
        "What OG HODLers taught, I teach.",
        "The good money drives out the bad - Thiers’ Law.",
        "This is my fundamental teaching."
    ]
  },
  {
    id: 43,
    title: "Chapter 43",
    content: [
        "The most intangible of all money",
        "overrides the hardest of all metals.",
        "That without substance preserves where there is no space for destruction.",
        "Hence I know the value of a digital storage of value.",
        "",
        "Spreading adoption without words,",
        "DCAing without action in my trading account-",
        "few in the world can grasp it's simplicity-",
        "that is the HODLer's way.",
        "Rare are those indeed",
        "who can accumulate 6.15 Bitcoin without selling."
    ]
  },
  {
    id: 44,
    title: "Chapter 44",
    content: [
        "What means more to you,",
        "your current losses or future gains?",
        "What adds more to your net worth,",
        "trading acumen or a buy-and-hold strategy?",
        "I say what you gain in complexity,",
        "is what you lose in effectiveness.",
        "",
        "Wealth is the fruit of savings and discipline.",
        "HODLing bitcoin is the result of unwavering conviction and 10,000 hours of studying.",
        "",
        "A confident bitcoiner doesn't panic during crashes.",
        "He who knows when to buy the dip is preserved from panic selling,",
        "only then can you endure to see the gains from future Halvings."
    ]
  },
  {
    id: 45,
    title: "Chapter 45",
    content: [
        "The perfect money seems imperfect,",
        "and yet its use cases are limitless.",
        "It does not have a venture backing,",
        "and yet its upside is parabolic.",
        "",
        "Great monetary policy seems confusing.",
        "Great inventions seem like fads.",
        "Great investments seem risky.",
        "Great truths seem false.",
        "Great revolution seems disorganized.",
        "",
        "Supply cap conquers inflation;",
        "Transaction fees surpass block subsidies.",
        "Using Bitcoin as a medium of exchange and unit of account",
        "is the next step for civilization."
    ]
  },
  {
    id: 46,
    title: "Chapter 46",
    content: [
        "When the people have bitcoin,",
        "they can save and plan for the future.",
        "When the people lack bitcoin,",
        "their savings and standards of living erode.",
        "",
        "There is no greater loss than trading time for infinite money,",
        "no greater crime than inflation,",
        "no greater tragedy than ignorance of fiat money;",
        "the worst of tricks is working more - yet getting less over time.",
        "",
        "Bitcoin savings alone is enough.",
        "Indeed, the freedom from government tyranny can be found in your own private keys."
    ]
  },
  {
    id: 47,
    title: "Chapter 47",
    content: [
        "Without broadcasting a transaction,",
        "know its uncensorability.",
        "Without even reading The 7th Property,",
        "you may know the path to financial freedom.",
        "",
        "The farther down the rabbit hole one goes, the less one knows.",
        "Therefore the bitcoiner does not study",
        "and yet understands sound money intuitively.",
        "He does not strive to outperform DCA",
        "and yet his stacking goal is still attained."
    ]
  },
  {
    id: 48,
    title: "Chapter 48",
    content: [
        "Stacking sats consists of daily accumulating.",
        "Getting on Zero Fiat consists of daily diminishing;",
        "selling fiat to unplug from the matrix, until no paper money remains.",
        "When Zero Fiat is reached, no personal value is left to be inflated away.",
        "",
        "True Bitcoin adoption can be reached",
        "by letting the pain of inflation become unignorable.",
        "It cannot be achieved by force or interference."
    ]
  },
  {
    id: 49,
    title: "Chapter 49",
    content: [
        "The bitcoiner has no fixed price target;",
        "he is aware of the laws of supply and demand.",
        "",
        "Those who promote Bitcoin he treats with reverence.",
        "Those who attack Bitcoin he also treats with reverence",
        "because bitcoins path to monetization is assured.",
        "",
        "He is kind to the plebs.",
        "He is also kind to the shitcoiners,",
        "because the nature of a bitcoiner",
        "is community.",
        "",
        "He is loyal to his local Bitcoin meetup,",
        "but is also loyal to his normie friends.",
        "He lives in harmony",
        "through the Fourth Turning.",
        "He sees everything as a season;",
        "each saeculum, a role to play.",
        "",
        "All freedoms will be afforded to him,",
        "He behaves like a Sovereign Individual."
    ]
  },
  {
    id: 50,
    title: "Chapter 50",
    content: [
        "Between Bitcoiners today,",
        "three in ten are users of custodians;",
        "three in ten hold equity in treasury companies.",
        "And those who 'just buy the ETF instead\"",
        "also number three in ten.",
        "",
        "Why is this so?",
        "Because they clutch to the familiar",
        "and cling to their old, antiquated ways.",
        "",
        "But there is one in ten, they say, so sure of self-custody",
        "that class action lawsuits and capital gains will never afflict him.",
        "Dusters add more sats to his wallet,",
        "he got off Gox before it collapsed,",
        "he's never lent his coins to BlockFi,",
        "and rumor has it, he doesn't care about yield.",
        "",
        "Why is this so?",
        "Because self-custody makes your wealth invincible,",
        "when life's opportunities can not be robbed through moral hazard or inflation.",
        "",
        "Realize the once-in-a-species discovery",
        "and your legacy will last for generations."
    ]
  },
  {
    id: 51,
    title: "Chapter 51",
    content: [
        "Bitcoin connects all humans under one fair Monetary System.",
        "It sprung into existence in 2009,",
        "pseudonymously, near perfect, to promote freedom;",
        "It took on a life of its own;",
        "let exponentially growing hashrate secure it's future.",
        "",
        "Therefore all beings can recognize its independence",
        "and value its savings power.",
        "They have not been forced to hold Bitcoin,",
        "but do so by choice, out of rational economic incentives.",
        "",
        "Bitcoin gives them hope.",
        "It's purchasing power preservation nourishes and protects their livelihoods.",
        "Bitcoin creates opportunities and not oppression;",
        "equivocally open to all;",
        "unites others through simple protocol rules;",
        "and aligns citizens incentives across the world.",
        "This is called the peaceful revolution."
    ]
  },
  {
    id: 52,
    title: "Chapter 52",
    content: [
        "All those holding bitcoin have a common beginning.",
        "This beginning is understanding the Federal Reserve System.",
        "Having known the \"hamster wheel\" arrangement we're put on,",
        "we may proceed to look for alternatives.",
        "Having known a taste of freedom,",
        "we should go back and convert all our fiat to hard money.",
        "",
        "Don't talk about your bitcoin,",
        "guard your private keys",
        "and wealth will be accumulated.",
        "Talk about your stack,",
        "brag with lambos and high-time preference behavior,",
        "and your Bitcoin won't be yours for long.",
        "",
        "Seeing value in the smallest unit of account is called \"Sats, the Standard.\"",
        "HODLing through multiple halvings in self-custody is called \"having diamond hands.\"",
        "Following the verifiable truth will save you from misfortune.",
        "",
        "This is called",
        "don't trust, verify."
    ]
  },
  {
    id: 53,
    title: "Chapter 53",
    content: [
        "If I have even just a little sense,",
        "I should buy some Bitcoin just in case it catches on,",
        "and my only fear would be being too late.",
        "",
        "Accumulating Bitcoin is simple and easy,",
        "yet the people prefer devious paths.",
        "That is why the Federal Reserve is corrupt,",
        "congressmembers insider trade,",
        "and the debt ceiling is infinite.",
        "",
        "Flying private jets,",
        "wearing fancy jewelry,",
        "indulging in the finest food and drink,",
        "amassing a large Bitcoin fortune to the extent of not knowing to do with it,",
        "is being like a Cantillionaire.",
        "",
        "I say this lifestyle at the expense of others is like bragging on X after a rugpull.",
        "This is not the Bitcoin Tao."
    ]
  },
  {
    id: 54,
    title: "Chapter 54",
    content: [
        "Whoever's savings are in bitcoin",
        "will not be inflated away.",
        "Whoever embraces DCA & self-custody",
        "will not be left behind.",
        "",
        "Generations will revere your hodl strategy.",
        "Rooted in low time preference, opportunity is realized;",
        "based on not trusting but verifying, conviction strengthens;",
        "cultivated in a local community, momentum increases,",
        "rooted in a desire to separate money from state, freedom for all abounds.",
        "",
        "Bitcoin is everywhere;",
        "it will become synonymous with \"money.\"",
        "To truly understand it, see it is a breakthrough.",
        "In a person, see it as a tool for sovereignty;",
        "in a family, see it as a means of support;",
        "in a country, see it as a vessel for opportunity;",
        "in the world, see it as a movement towards freedom.",
        "",
        "How do I know this is true?",
        "I've spent thousands of hours studying Bitcoin."
    ]
  },
  {
    id: 55,
    title: "Chapter 55",
    content: [
        "He whose node is in consensus with their peers",
        "is like a sovereign citizen.",
        "Corrupt governments will not stop his transactions.",
        "Miners will not reject his pool shares.",
        "Block reorganizations will not affect him.",
        "His data usage is minimal, his hard drive space aplenty,",
        "yet his freedom to transact is unmatched.",
        "",
        "He may not have ever flagged RBF or CPFP, but knows his ordering of transactions is correct.",
        "His reliability is high.",
        "He runs his node 24/7 without overheating.",
        "He doesnt use a Raspberry Pi.",
        "",
        "To know the block height is to know the most recent timestamp;",
        "to know the current hashprice is to have insight into mining conditions.",
        "Things in harmony with reinforcing incentives remain;",
        "things that are forced may last for a while,",
        "but then fade away.",
        "This is not the Bitcoin Tao.",
        "And whatever is against the Bitcoin Tao will become another data point of \"Bitcoiners were right again.\""
    ]
  },
  {
    id: 56,
    title: "Chapter 56",
    content: [
        "Those who stack sats do not worry.",
        "Those who worry do not stack sats.",
        "",
        "Sell all of your fiat!",
        "Close your bank account,",
        "spend the cash beneath your mattress,",
        "empty your vault of gold,",
        "srengthen your conviction,",
        "teach the importance of self-custody,",
        "sell your chairs.",
        "This is going all in on a once-in-a-species invention.",
        "",
        "One who realizes this opportunity",
        "is not scared off by narratives or volatility,",
        "swayed by unrealized profit or loss,",
        "nor caught up in the scams on CoinMarketCap.",
        "He is far beyond your 100x day trader",
        "yet has a bigger stack than they ever will.",
        "",
        "Thus, being a bitcoin-only hodler is the highest returning savings strategy."
    ]
  },
  {
    id: 57,
    title: "Chapter 57",
    content: [
        "If you want to be a great bitcoiner,",
        "you must start attending your local meetup.",
        "Stop trying to remain anonymous.",
        "Let go of your concern of endorsing Bitcoin publicly,",
        "and the world will achieve hyperbitcoinization sooner.",
        "",
        "How do I know this is so?",
        "Because in this world,",
        "the greater the perceived risk of being wrong,",
        "the more timid people become;",
        "the more successful the propaganda,",
        "the more one doubts their own intuition;",
        "the more isolated the people feel,",
        "the more divisive rhetoric becomes;",
        "the less understanding we all possess,",
        "the longer the world remains ignorant of a better alternative.",
        "",
        "Therefore the bitcoiner says:",
        "I teach about the problem of fiat before bitcoin.",
        "I don't spread prophecy but ideas.",
        "I increase my purchasing power just from being patient.",
        "If I keep from selling my Bitcoin to stronger hands,",
        "I can increase my standard of living over time."
    ]
  },
  {
    id: 58,
    title: "Chapter 58",
    content: [
        "When the people have sound money,",
        "their lives are enjoyable and free.",
        "When the government meddles with the medium of exchange,",
        "they become overworked and underpaid.",
        "",
        "Ignorance of better alternatives is what fiat money depends on;",
        "The term \"crypto\" is what scam projects hide under.",
        "Who knows when Gary Gensler will be fired?",
        "Is there no definition of \"blatant scam\" at the SEC?",
        "Yet a brilliant innovation is soon conflated with \"get rich quick scheme\" or cult;",
        "long term adoption will indeed take a while.",
        "",
        "Thus the bitcoiner is content to serve as an example",
        "and to not impose peer pressure.",
        "His intellect is sharp but does not belittle;",
        "his examples are compelling but not confusing;",
        "his proof of work influences but does not force."
    ]
  },
  {
    id: 59,
    title: "Chapter 59",
    content: [
        "In changing the rules of the protocol,",
        "nothing surpasses slow and marginal improvements.",
        "",
        "Restraint begins with giving up ones own ideas about how Bitcoin should be.",
        "This depends on experience learned from the blocksize wars.",
        "If there is a working store of value, then perhaps nothing should be changed.",
        "Yet if nothing is changed, then there is no scaling.",
        "If a man knows this conundrum, he is fit to submit a pull request.",
        "",
        "This is the way to get deeply aware",
        "and firmly focused on security,",
        "the secret to a long and lasting monetary network."
    ]
  },
  {
    id: 60,
    title: "Chapter 60",
    content: [
        "Governance of a decentralized blockchain",
        "is like a finely tuned watch.",
        "You weaken it with too many changes.",
        "",
        "Approach draft BIPs with caution",
        "and unintended use cases will not prevail.",
        "Not that upgrades aren't allowed,",
        "but first ensure its usage will not harm other users.",
        "Only if the soft forks benefit all,",
        "should the bitcoiner himself promote a change.",
        "",
        "If only the plebs would keep from rushing in new BIPs",
        "that could harm the protocol security,",
        "all the benefits of a sound monetary network would be shared",
        "to the world."
    ]
  },
  {
    id: 61,
    title: "Chapter 61",
    content: [
        "A great monetary asset is the base layer",
        "toward which all medium of exchange will flow.",
        "It is the store of value of humans and machines alike,",
        "the denomintator of all transactions.",
        "Bitcoin overcomes fiat dominance through survival,",
        "by remaining a constant through the storm.",
        "",
        "So if a fiat government follows bitcoiners,",
        "they'll start stacking sats and see progress.",
        "If bitcoiners orange-pill a great nation,",
        "they will enrich that nation and its people.",
        "One wins by stacking sats",
        "the rest, by staying humble."
    ]
  },
  {
    id: 62,
    title: "Chapter 62",
    content: [
        "Bitcoin is a treasure,",
        "the perfect monetary asset,",
        "the secret to 21st century prosperity.",
        "It is the savings tool for the good",
        "and an affinity scam for the bad.",
        "",
        "If a person seems like they're shitcoining,",
        "do not cast him away.",
        "Give him the orange pill,",
        "teach him about Bitcoin Script,",
        "repay his degeneracy with generosity.",
        "Do not cast him away;",
        "cast away his confusion.",
        "",
        "Thus when a new narrative arises,",
        "do not try to dismiss it",
        "with your reputation or expertise.",
        "Meditate on the principles of sound money;",
        "offer instead to teach others about the blockchain trilemma and path dependency.",
        "",
        "Why did Bitcoin OGs take so much care into preventing hard forks?",
        "Is it not because bitcoin is the source of monetary truth,",
        "an immutable ledger for all?",
        "It is the most important invention of our lifetime."
    ]
  },
  {
    id: 63,
    title: "Chapter 63",
    content: [
        "Practice HODLing,",
        "build wealth through patience.",
        "DCA every day.",
        "Withdraw to self custody, back up your seed phrase.",
        "See drawdowns as opportunities.",
        "See clarity in the chaos.",
        "Achieve wisdom through survival.",
        "",
        "Build projects during bear markets;",
        "manage UTXOs when fees are low.",
        "The bitcoiner does not attempt to trade with leverage,",
        "and thus understands continuous compounding growth.",
        "",
        "If you sell for fiat too quickly, your wealth will not last long;",
        "because the bitcoiner always spends and replaces,",
        "his net worth never stops growing."
    ]
  },
  {
    id: 64,
    title: "Chapter 64",
    content: [
        "A draft BIP is easily submitted.",
        "What is not assigned a BIP number is easy to overlook.",
        "The soft forks are easily contentious;",
        "the hard forks are easily a nonstarter.",
        "",
        "Promote your idea before Speedy Trial;",
        "get developer mailing list approval before going public.",
        "Remember:",
        "There's nothing more powerful than an idea whose time has come.",
        "A multi-trillion dollar monetary protocol starts with one line of code",
        "A lifetime of incremental improvements starts with a single pull request.",
        "",
        "Meddle and destroy it; control it and lose its value.",
        "The developer does not create consensus forks, and so makes Bitcoin stronger.",
        "He does not try to \"Change The Code.\"",
        "Beginners usually lose the plot right when they're on the verge of Bitcoin maximalism.",
        "So take as much care as a veteran developer,",
        "as you did in the beginning.",
        "",
        "The Core dev does not merge unlinted code;",
        "He does not submit a PR without multiple reviews;",
        "he learns to express his ideas succinctly.",
        "He helps the rest of the community understand what Bitcoin could be",
        "but does not claim to know what Bitcoin is."
    ]
  },
  {
    id: 65,
    title: "Chapter 65",
    content: [
        "The OG Bitcoiners had a simple focus",
        "and wanted permissionless peer-to-peer money.",
        "They did not use \"Bitcoin bridges\";",
        "or trust their funds with DLCs,",
        "so their coins were truly theirs.",
        "",
        "When they think they know what code to merge,",
        "changes are difficult to implement",
        "When they know they do not know",
        "code can be merged",
        "",
        "Not using forced upgrades to govern a protocol",
        "is good indicator of the its health.",
        "The simplest primitives are the clearest.",
        "Content with the right to send and receive,",
        "you can show people the way",
        "back to bitcoin's original purpose."
    ]
  },
  {
    id: 66,
    title: "Chapter 66",
    content: [
        "Why is Bitcoin king of 10,000+ cryptos?",
        "Because it stands before all, relatively unchanged.",
        "Backwards compatibility gives it power.",
        "",
        "Therefore, those desiring a stable monetary protocol",
        "must move carefully.",
        "Those desiring to improve Bitcoin must first study its history.",
        "",
        "Thus, it is when a bitcoiner proclaims about the trappings of fiat currency,",
        "they do not feel the heaviness of his bags,",
        "and when he promotes a savings strategy in public,",
        "they do not feel \"sold to\"",
        "",
        "He stays humble",
        "so the world never knows how much he's stacked.",
        "He remains a pleb",
        "so the world never tires of paying him in bitcoin."
    ]
  },
  {
    id: 67,
    title: "Chapter 67",
    content: [
        "All of the world talks about Bitcoin",
        "with such familiarity-",
        "how naive!",
        "Bitcoin is not something you learn in 15 minutes",
        "or is taught by mainstream media.",
        "It is not something you learn accidentally",
        "or easily forget.",
        "If Bitcoin were like this,",
        "it would have ended like the tulip bubble long ago.",
        "",
        "I have three treasures, which I hold tightly",
        "and watch closely.",
        "The first, a full node.",
        "The second is private keys.",
        "The third, my S9.",
        "",
        "From a full node comes peer-to-peer transactions.",
        "From private keys comes the permissionless nature.",
        "From my S9, proof of work.",
        "Now if one sent peer-to-peer without a node,",
        "if one claimed sovereignty without their own keys,",
        "if one didn't exhibit their own fair share of hashrate",
        "Bitcoin would fail.",
        "",
        "Aligned incentives vanquish forks,",
        "It is impregnable to attackers.",
        "When the blockchain secures value for all,",
        "does it do so with an army?",
        "No, it does it with math."
    ]
  },
  {
    id: 68,
    title: "Chapter 68",
    content: [
        "A good upgrade is not consensus-breaking.",
        "A good core dev is not in a political.",
        "Good PRs do not create contention.",
        "Good miners don't censor block templates.",
        "The best BIP follows the will of economic incentives.",
        "",
        "All of them embody the virtue of cooperation.",
        "This is called the beauty of elegant design.",
        "This is called the actualization of bitcoin's potential.",
        "",
        "This since the first block has been known as peer-to-peer money."
    ]
  },
  {
    id: 69,
    title: "Chapter 69",
    content: [
        "There is a saying among Bitcoiners",
        "I dare not spend a sat",
        "but would rather HODL forever;",
        "I dare not cash out",
        "but would rather DCA",
        "",
        "This is called",
        "using Bitcoin as a store of value,",
        "using one property but not another.",
        "",
        "There is no greater mistake",
        "than not spending bitcoin;",
        "for when Bitcoin is not spent,",
        "there is no room for adoption.",
        "",
        "Thus when Thier's and Gresham's law meet,",
        "the need for a medium of exchange",
        "will triumph.",
        "",
        "When two forces are evenly strong,",
        "the one with long term sustainability wins."
    ]
  },
  {
    id: 70,
    title: "Chapter 70",
    content: [
        "Bitcoin is very to easy to understand",
        "and very easy to use;",
        "yet so few in this world understand it,",
        "and so few are willing to learn.",
        "",
        "Its beginning has an ancestor,",
        "the goal, a simple motive.",
        "The people have no knowledge of this",
        "therefore they have no knowledge of the solution.",
        "",
        "This is why the Bitcoiner dresses plainly,",
        "even though his wallet is full of UTXOs from the 1st epoch."
    ]
  },
  {
    id: 71,
    title: "Chapter 71",
    content: [
        "Spending fiat is sensible.",
        "Saving fiat is futile.",
        "",
        "Only when we are sick of our circumstances",
        "shall we seek change and save in bitcoin.",
        "The Bitcoiner is not discouraged by inflation but the lack of understanding of it;",
        "this is the secret of his unwavering conviction."
    ]
  },
  {
    id: 72,
    title: "Chapter 72",
    content: [
        "When the people lack a basic understanding of Bitcoin,",
        "mistakes in development will be made.",
        "When people do not fear recursivity,",
        "a greater complexity will be unveiled.",
        "",
        "Do not limit the potential of bitcoin.",
        "Do not despise the timing of your first purchase.",
        "Do not resist the natural course of development.",
        "In this way you will never weary of being a bitcoiner.",
        "",
        "Therefore the Bitcoiner studies the code",
        "but doesn't participates public PR debates;",
        "reads to learn",
        "but does not try to influence others.",
        "He prefers his own conviction over group confirmation bias."
    ]
  },
  {
    id: 73,
    title: "Chapter 73",
    content: [
        "Saving in fiat leads to ruin.",
        "Saving in bitcoin leads to freedom.",
        "Both of these choices",
        "sometimes reward",
        "and sometimes humble you.",
        "",
        "It is bitcoin's way to secure without force.",
        "It does not command, yet nodes cooperate.",
        "It does not promise, yet scarcity remains absolute.",
        "It does not have a schedule, yet it confirms roughly every 10 minutes.",
        "",
        "The chain of Bitcoin settles all transactions; its blocks are slow,",
        "but no record is missing from its ledger."
    ]
  },
  {
    id: 74,
    title: "Chapter 74",
    content: [
        "If you realize bitcoin itself must change,",
        "there is no version you will cling to forever.",
        "If you do not fear bitcoin's uncertain future,",
        "there is no upgrade you cannot navigate.",
        "",
        "Yet there is always the unknown beyond each upgrade.",
        "He who tries to force bitcoin's destiny",
        "is like one who alters the course",
        "of a mighty river.",
        "Whoever tries to alter the flow of a mighty river",
        "is certain to be swept away."
    ]
  },
  {
    id: 75,
    title: "Chapter 75",
    content: [
        "When inflation is too high, people's time is stolen.",
        "When the government controls the money,",
        "people's wealth silently disappears.",
        "",
        "Let bitcoin restore value to people's work;",
        "trust their choices, leave their money alone."
    ]
  },
  {
    id: 76,
    title: "Chapter 76",
    content: [
        "Bitcoin was born quiet and fragile;",
        "at its genesis, vulnerable and niche.",
        "All systems, including code and consensus itself,",
        "are adaptive and humble in the beginning;",
        "rigid and unchanging near their end.",
        "",
        "Thus, adaptability is the companion of growth;",
        "inflexibility, a companion of decline.",
        "Consensus that cannot change",
        "will eventually split apart.",
        "A plan that can't adapt",
        "will split from its own strength.",
        "",
        "The sturdy and rigid will eventually fracture;",
        "the resilient and adaptive will prevail."
    ]
  },
  {
    id: 77,
    title: "Chapter 77",
    content: [
        "The way of open source",
        "is like balancing a scale:",
        "When code is scarce, it is created;",
        "When code is abundant, it is shared.",
        "",
        "If knowledge is lacking, it's provided;",
        "If knowledge is in surplus, it's freely distributed.",
        "The way of fiat is the opposite:",
        "It creates false scarcity",
        "to profit from its artificial surplus.",
        "It locks away knowledge to enrich those who already have enough.",
        "",
        "Only the one who follows open-source principles",
        "offers his surplus to the world.",
        "What developer has more than enough",
        "and shares his work freely with all?",
        "Only one aligned with Satoshi.",
        "",
        "The bitcoiner can keep giving",
        "because his wealth compounds forever.",
        "He codes without expectation,",
        "builds without taking credit,",
        "and never believes his commits are above another dev's."
    ]
  },
  {
    id: 78,
    title: "Chapter 78",
    content: [
        "Nothing in the world is quieter",
        "and stronger than silent conviction.",
        "Yet, for overcoming fear, uncertainty, and doubt,",
        "nothing can surpass it.",
        "There is nothing like it.",
        "",
        "The hodler outlasts the trader;",
        "the stacker defeats the degen.",
        "In all of crypto twitter, everyone understands this truth,",
        "yet very few follow it consistently.",
        "",
        "Therefore the bitcoiner remains calm during selloffs;",
        "FUD does not enter his mind.",
        "Because he does not rush global adoption,",
        "he is adoption's greatest catalyst.",
        "",
        "Hard money is invisible; paradoxical."
    ]
  },
  {
    id: 79,
    title: "Chapter 79",
    content: [
        "After a contentious fork, much uncertainty remains.",
        "How should one respond?",
        "Holding calmly onto the original chain",
        "is usually best in the end.",
        "",
        "Someone must risk trading new forked coins for bitcoin,",
        "or confusion will never turn to clarity.",
        "Thus, the wise hold without worry of loss.",
        "",
        "One who trusts bitcoin's path",
        "always knows which chain of work to follow.",
        "One who lacks conviction",
        "chases forks hoping to gain more.",
        "To the hodler comes abundance;",
        "to the speculator, a worthless wallet."
    ]
  },
  {
    id: 80,
    title: "Chapter 80",
    content: [
        "Imagine a humble life, quietly stacking sats.",
        "They have fiat but rarely spend it;",
        "they savor the fruit of their own labor,",
        "and do not chase quick profits through schemes.",
        "",
        "They value scarcity deeply and do not waste sats.",
        "Since they understand Bitcoin's rarity,",
        "they find satisfaction in just saving.",
        "Though opportunities to spend money surround them,",
        "they prefer restraint.",
        "",
        "They are content with simple pleasures,",
        "pleased by lasting quality,",
        "satisfied with proof-of-work,",
        "and protective of their low time-preference lifestyle.",
        "",
        "Though they see neighbors caught up in endless spending,",
        "and the noises of consumption",
        "are all around,",
        "they quietly stack, leaving others in peace,",
        "while they grow generational wealth patiently over time."
    ]
  },
  {
    id: 81,
    title: "Chapter 81",
    content: [
      "True wealth is not measured;",
      "measured wealth is not true.",
      "Bitcoiners do not hoard possessions;",
      "those who hoard are not bitcoiners.",
      "Those who value time won't worship money;",
      "those who worship money dont understand time.",
      "",
      "The wise bitcoiner accumulates sats",
      "to enrich their life and others';",
      "the more they enrich others',",
      "the richer they become.",
      "",
      "Fixing the money will bring prosperity to all,",
      "doing harm to none.",
      "The bitcoiner knows it:",
      "using sound money to repair what is broken,",
      "and opposing himself to the injustice of fiat currency."
    ]
  }
];

export const NAV_ITEMS: Array<{label: string, view: View, href?: string}> = [
  { label: 'Home', view: View.HOME },
  { label: 'About', view: View.ABOUT },
  { label: 'Book', view: View.BOOK },
  { 
    label: 'Denver BitDevs', 
    view: View.DENVER_BITDEVS, 
    href: 'https://youtube.com/playlist?list=PLNqRMbxvh6R5OjnNTFVYbfV-JYaHco4nZ&si=D9ghmUhXdfZlZsrK' 
  },
  { 
    label: 'The Space', 
    view: View.THE_SPACE, 
    href: 'https://denver.space' 
  },
  { 
    label: 'Podcast', 
    view: View.PODCAST, 
    href: 'https://youtube.com/playlist?list=PLNqRMbxvh6R60edSJfDhy9fZJk516Z3o4'
  },
  { 
    label: 'Contact', 
    view: View.CONTACT, 
    href: 'https://t.me/btcbap' 
  },
];